# Generated by Django 5.0.6 on 2024-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_slug_remove_category_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
